dotnetapp:
  build: "./app-server"
  container_name: "dotnetapp"
  working_dir: "/usr/src/dotnetapp/WebSite1"
  ports:
   - "5000:5000"
  volumes:
   - "./src/WebSite1:/App"
  command: ["dotnet", "watch", "run"]
mssql:
    build: "./mssqlserver"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=56CFUVzh # パスワードポリシー(https://docs.microsoft.com/ja-jp/sql/relational-databases/security/password-policy?view=sql-server-ver15)
      - MSSQL_PID=Express # SQL Serverのエディションまたはプロダクトキー
      - MSSQL_LCID=1041 # ロケールID 日本語 (https://www.ryadel.com/en/microsoft-windows-lcid-list-decimal-and-hex-all-locale-codes-ids/)
      - MSSQL_COLLATION=Japanese_CI_AS # 照合順
      - DB_NAME=DEMO # 初回起動時のDB存在判定のために使用します。
    volumes:
      - ./mssqlserver/initdb.d:/docker-entrypoint-initdb.d
      - ./mssqlserver/data:/var/opt/mssql/data
      - ./mssqlserver/log:/var/opt/mssql/log
      - ./mssqlserver/secrets:/var/opt/mssql/sec